name: amanoo_app
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.1.2 <4.0.0"

dependencies:
  dartz: ^0.10.1
  dio: ^5.3.3
  email_validator: ^2.1.17
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_i18n: ^0.34.0
  flutter_launcher_icons: ^0.13.1
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.4.2
  flutter_secure_storage: ^9.0.0
  font_awesome_flutter: ^10.5.0
  freezed_annotation: ^2.4.1
  get_it: ^7.6.4
  go_router: ^12.0.0
  google_fonts: ^6.0.0
  intl: ^0.18.1
  json_annotation: ^4.8.1
  riverpod_annotation: ^2.1.6
  shared_preferences: ^2.2.2

dependency_overrides:
  font_awesome_flutter:
    path: ./packages/font_awesome_flutter

dev_dependencies:
  build_runner: ^2.4.6
  custom_lint: ^0.5.3
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.5
  go_router_builder: ^2.3.3
  json_serializable: ^6.7.1
  riverpod_generator: ^3.0.0-dev.2
  riverpod_lint: ^2.2.1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/fonts/mazzardh/
    - assets/fonts/open_sans/
    - assets/icon/
    - assets/legales/
    - assets/loading/
    - assets/logo/
    - assets/lottie/
    - assets/menu/
    - assets/redes/
    - .env

  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/open_sans/OpenSans-Regular.ttf
        - asset: assets/fonts/open_sans/OpenSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/open_sans/OpenSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/open_sans/OpenSans-Italic.ttf
          style: italic
    - family: Mazzard
      fonts:
        - asset: assets/fonts/mazzardh/MazzardH-SemiBold.ttf
          weight: 600
